[package]
name = "volt"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["examples/*"]

[workspace.dependencies]
volt = { version = "0.1", path = "." }

[dependencies]
env_logger = "0.10.0"
log = "0.4.20"
wgpu = "0.17"
winit = "0.28"
